### ISSUE TITLE
Command blocker

### ISSUE THREAD

**Issue by Telesphoreo** [plexusorg/Plex#10]
The command blocker should be in Plex (not a module)

Here's some of the things it should have
- [x] A separate commands.yml file
- [x] Different levels of blocked commands
  - [x] Everyone
  - [x] Everyone except Admins+
  - [x] Everyone except Senior Admins+
- [x] A section plain matching
  - [x] If a person enters just a command (example `tpall`) it will block the entire command. If they enter `mail sendall` for example, block the `mail` command and all aliases plus the argument "sendall". This should also account for aliases (e.g. `etpall` or `email`
- [x] A section for RegEx matching. People can create RegEx and if it matches, it will block the command

An example format might be this:
`<regex or match>:<rank>:command name no slash:Block message`

Symbols to use:
  - r for RegEx
  - m for matching
  - The ranks should be "e" for everyone, "a" for admin and "s" for senior admin
  - The command is just the command without slashes. Optional arguments will be there also
  - Finally the block message. We can have a _ represent a default "This command is blocked" message, or you can optionally put your own in

So these would be valid:
`"m:e:mail sendall:You cannot send messages to everyone on the server"`
`"r:e:(.*:):Plugin specific commands are disabled"`

**Comment by Focusvity** [comment]
I'll give this a go

**Comment by Telesphoreo** [comment]
Closed in [a58b6fb](https://github.com/plexusorg/Plex/commit/a58b6fbba800ee2b6ec525792fdc41a77d884dad)
