### ISSUE TITLE
World entry

### ISSUE THREAD

**Issue by Telesphoreo** [plexusorg/Plex#12]
This doesn't have to be in Plex before 1.0, but I'm opening it anyway

Basically, this should forbid people from entering the adminworld if they're not an admin. Obviously, since the adminworld isnt hardcoded, it should be configurable for every world in the config.

```java
    // TODO: Add an entry setting in the config.yml and allow checking for all worlds
    @EventHandler
    public void onWorldTeleport(PlayerTeleportEvent e)
    {
        final World adminworld = Bukkit.getWorld("adminworld");
        PlexPlayer plexPlayer = DataUtils.getPlayer(e.getPlayer().getUniqueId());
        if (e.getTo().getWorld().equals(adminworld) && !plexPlayer.isAdminActive())
        {
            e.setCancelled(true);
        }
    }
```
This is what it looks like right now

I'd say do something like
1. If the world exists in the config then
2. Read an "entry" value that's just a rank or a Title
3. If the person is not equal to or higher than the rank, cancel the event

**Comment by Paldiu** [comment]
The issue with the code listed above is that if there is no actual adminworld present then it will throw an NPE

**Comment by ayunami2000** [comment]
oh wait apparently its not as configurable as we want it to be yet
