### ISSUE TITLE
NBT Lecterns

### ISSUE THREAD

**Issue by ayunami2000** [plexusorg/Plex#19]
filter nbt reading from these on place. this will prevent a lot of things, namely **reading any player's coordinates or inventory contents via nbt**.

this would also have to be applied to signs.

**Comment by Telesphoreo** [comment]
This should go in Blackout honestly

**Comment by ayunami2000** [comment]
I agree, so maybe we transition current patches that already should be in blackout over to it, then patch this in blackout?

**Comment by Telesphoreo** [comment]
Yes
