### ISSUE TITLE
AntiSpam and AntiNuke

### ISSUE THREAD

**Issue by Telesphoreo** [plexusorg/Plex#21]
Prevent sending too many messages or breaking blocks quickly with a nuker.

A three strike system will do
1. Kick them
2. Temp ban them for 5 minutes
3. Ban for day

**Comment by ayunami2000** [comment]
antispam should also not be active at times when the server is lagging, maybe using system time to judge the time between messages or something

**Comment by fyyv** [comment]
I think that the kick and tempban messages for nuker should contain instructions to disable nuker from a singleplayer world. It will reduce the amount of innocent players caught up in the system.
