### ISSUE TITLE
Add the ability to manually purge all entities

### ISSUE THREAD

**Issue by fyyv** [plexusorg/Plex#23]
I would like to see a flag added to some command, or a new command added entirely, to clear all entities except specific ones specified in config. Currently we have mobpurge but we don't have entitypurge, and entitywipe does not have an `all` flag.

**Comment by Telesphoreo** [comment]
I suppose we could add an entitywipe -a flag. Entitywipe will purge everything except what's specified in the config.yml (and players obviously)

**Comment by Telesphoreo** [comment]
Sorry but I don't think it's a good idea to override the config by normal players so I'm going to close this
