### ISSUE TITLE
Entities whose names contain spaces do not work in entitywipe

### ISSUE THREAD

**Issue by fyyv** [plexusorg/Plex#24]
Entity types are stored as string arrays in EntityWipeCMD. Due to their current format (made to look nice in autocomplete), you can't `/entitywipe` entities whose names contain spaces. For example, it thinks "Armor" and "Stand" are individual entity types, two separate arguments, both of which are invalid.

Quotes don't work and neither do things like `minecraft:armor_stand`, `armorstand`, nor `armor_stand`.

**Comment by Telesphoreo** [comment]
Fixed
