### ISSUE TITLE
Console users' names do not appear to be populated in consolesay

### ISSUE THREAD

**Issue by fyyv** [plexusorg/Plex#29]
From the console, I ran the command `consolesay Plex`

The output was `[<time> INFO]: [Console: CONSOLE] Plex`

I was expecting the output to be `[<time> INFO]: [Console: <username>] Plex`.

Note I am accessing the server at `localhost` from `localhost`. Is this working as intended, have I missed a step, or is there a problem?

**Comment by Telesphoreo** [comment]
Not able to reproduce. ![](https://packs.smokes-crystal.rocks/9gNgZ4oIwgmm.png)
