### ISSUE TITLE
Plugin-specific command example in commands.yml doesn't work

### ISSUE THREAD

**Issue by allinkdev** [plexusorg/Plex#47]

**Comment by Telesphoreo** [comment]
Can you be more specific

**Comment by Telesphoreo** [comment]
Can you include the command that you used to get this stacktrace

**Comment by Focusvity** [comment]
It seems to be pointing to this line: https://github.com/plexusorg/Plex/blob/master/server/src/main/java/dev/plex/services/impl/CommandBlockerService.java#L33

My guess is one of the commands in the file (`commands.yml`) isn't configured properly

**Comment by allinkdev** [comment]
> It seems to be pointing to this line: https://github.com/plexusorg/Plex/blob/master/server/src/main/java/dev/plex/services/impl/CommandBlockerService.java#L33
> 
> https://github.com/plexusorg/Plex/blob/master/server/src/main/resources/commands.yml#L55
> 
> I assume trying to execute a plugin-specific command would cause this stacktrace?

No, this error occurs by starting the server with the plugin-specific command block regex.

**Comment by Telesphoreo** [comment]
I am not able to reproduce this. I am going to need a lot more info

**Comment by Telesphoreo** [comment]
I've received your commands.yml file via Discord and wasn't able to reproduce this on my server with your file. I think the problem lies elsewhere
