### ISSUE TITLE
Add Report Command

### ISSUE THREAD

**Issue by Taahh** [plexusorg/Plex#70]

**Comment by VideoGameSmash12** [comment]
I actually worked on a rather polished report system that was to be used in a fork of the TotalFreedomMod called Liberation. It got far enough to where reports were broadcasted and there was a way to query them, but not far enough to where the reports themselves would be stored persistently.

Here's what the various messages looked like:
![image](https://github.com/plexusorg/Plex/assets/8041766/94c9f243-a715-4b80-a4ea-4e9ad0e2dff2)
![image](https://github.com/plexusorg/Plex/assets/8041766/e2c44138-e699-4dbd-83a4-633e4b79afaf)
![image](https://github.com/plexusorg/Plex/assets/8041766/8c7a46d4-239f-4f5a-a8f8-00b76c0024bc)

Should we re-use this to implement in Plex?

**Comment by Telesphoreo** [comment]
If it's going to be a complex thing rather than just a report command that broadcasts to online admins, we should consider keeping it a separate plugin or putting it in as a module
