### ISSUE TITLE
Entity wiping

### ISSUE THREAD

**Issue by Telesphoreo** [plexusorg/Plex#8]
The entity wiping should be a part of Plex (not a module). Here are some of the things it should have

- [x] A /rd [entity] command. Removes all entities specified in the config.yml. You can also specify an entity manually
- [x] A /mp [mob] command. Removes all mobs, no configuration. You can also specify just one type manually
- [x] An "autowiping" feature. In other words, remove all drops after a specific amount of time. For example, wipe all drops every 10 minutes. The duration should be configurable.
- [x] A toggle to immediately remove all block drops. This should overwrite the autowiper if it's enabled. In other words, if this is true, ignore the auto wiper. If it's false, drops will stay, but only for the time in the autowiper
- [x] A "toggledrops" command that will toggle whether drops should be wiped immediately

Also, I forgot to say, but we should make sure this isn't a part of Paper already

**Comment by ayunami2000** [comment]
ill do this

**Comment by ayunami2000** [comment]
[x] /rd
[ ] /mp
[ ] autowiping
[ ] immediately remove drops
[ ] /toggledrops

**Comment by ayunami2000** [comment]
forgot to make autowiping update upon plugin reload

**Comment by ayunami2000** [comment]
ok fixed now
