### ISSUE TITLE
Remove -nrb and replace with -rb for optional rollback

### ISSUE THREAD

**Issue by notsceptor** [plexusorg/Plex#91]
Rollbacks are only necessary for a specific ban reason (griefing), in which case it makes sense for the user to be rolled back. In any other scenario, rolling back isn't necessary. Having rollbacks enabled by default for any ban leads to a significant number of false bans.

Instead of the current approach, I propose an explicit `-rb` option to manually start the rollback process. This would mean that rollbacks aren't enabled by default, but can be used selectively when a grief-related ban occurs.

**Comment by kissingboys** [comment]
+1

**Comment by notsceptor** [comment]
Would also like to note that this is all that needs to be changed:

```java
String newReason = StringUtils.normalizeSpace(reason.replace("-rb", ""));
punishment.setReason(newReason.trim().isEmpty() ? "No reason provided." : newReason);
rollBack = reason.startsWith("-rb") || reason.endsWith("-rb");```
