### ISSUE TITLE
Allow world borders to be managed via config.yml

### ISSUE THREAD

**Issue by Deauthorized** [plexusorg/Plex#92]
Title. World borders would be configured per world via a `border` key in config.yml, following this structure;

border:
size: 10000
message: "<red>You cannot go that way."

Size refers to the max distance you can go from 0, 0 before encountering the world border. This will also require a separate listener for enforcing the world border properly, as Mojangs implementation only works for Survival mode.
   
`

**Comment by Deauthorized** [comment]
Github just fucking hates any kind of formatting it seems

**Comment by notsceptor** [comment]
object

**Comment by Telesphoreo** [comment]
We don't need this. We already use the WorldBorder plugin

**Comment by Deauthorized** [comment]
> We don't need this. We already use the WorldBorder plugin

Which allows you to just fly right past the border via spectator mode and columbus grief anyways.

**Comment by Telesphoreo** [comment]
So raise an issue with the dev of that plugin first.
