### ISSUE TITLE
Implement a /names feature

### ISSUE THREAD

**Issue by notsceptor** [plexusorg/Plex#98]
I'm pretty sure we had something similar on TFM that allowed you to view old names of players. Looking up player names is something I do quite a bit if there's a name I'm unfamiliar with, so it'd be handy to have it as an ingame feature. I'm pretty sure you can utilise namemc's API to do this?

**Comment by Telesphoreo** [comment]
We used to have this but Mojang got rid of the API that allowed it, so we removed the command.

**Comment by Taahh** [comment]
I'll be closing this issue, I don't think there is a possible discussion needed on this for the reason Telesphoreo stated.
